#!/bin/bash
# changeVolume

# Arbitrary but unique message id
msgId="100"

# Change the volume using alsa(might differ if you use pulseaudio)
# a me non serve in realta
# amixer set Master "$@" > /dev/null

# Query amixer for the current volume and whether or not the speaker is muted
volume="$(amixer get Master | tail -1 | awk '{print $5}' | sed 's/[^0-9]*//g')"
mute="$(amixer get Master | tail -1 | awk '{print $6}' | sed 's/[^a-z]*//g')"
if [[ $volume == 0 || "$mute" == "off" ]]; then
	    # Show the sound muted notification
	        dunstify -a "changeVolume" -u low -i audio-volume-muted -r "$msgId" "Volume muted" 
	else
		    # Show the volume notification
		        dunstify -a "changeVolume" -u low -i audio-volume-high -r "$msgId" \
				    "Volume: ${volume}%" "$(bar 34 $volume)"
fi
