#!/bin/bash

if [[ $(playerctl status 2>&1) != "No players found" ]]; then
	artist=$(playerctl metadata artist)
	title=$(playerctl metadata title)
	get_status=$(playerctl status)
	status=$(
		case $get_status in
			Playing)
				echo ' '
				;;
			Paused)
				echo ' '
				;;
			Stopped)
				echo ' '
				;;
			*)
				echo 'stop'
				;;
		esac
		  )

	echo "$status" "$artist": "$title"
else
	echo ''
fi
